### ISSUE TITLE
Weight-Alignement model

### ISSUE THREAD

**Issue by arthurdouillard** [Rhyssiyan/DER-ClassIL.pytorch#11]
I've been trying to reproduce your results of WA using my codebase (original inclearn) unsuccessfully.

And when I'm looking at your codebase I see that WA is not yet implemented? The distillation https://github.com/Rhyssiyan/DER-ClassIL.pytorch/blob/main/inclearn/models/incmodel.py#L73 is never used. Am I missing something or did you not yet uploaded the code & configs of your baselines?

**Comment by Rhyssiyan** [comment]
Hi, we have updated the code of WA put in exps folder recently.  You can check it now.
