### ISSUE TITLE
Subset of Classes Used for ImageNet-100

### ISSUE THREAD

**Issue by ardywibowo** [Rhyssiyan/DER-ClassIL.pytorch#12]
Hello,
Which subset of classes of the full ImageNet-1000 did you use for ImageNet-100? Is it the first 100 classes in alphabetical order of the folder names? Thanks!

**Comment by Rhyssiyan** [comment]
Hi, you can find it in the file https://raw.githubusercontent.com/arthurdouillard/incremental_learning.pytorch/master/imagenet_split/train_100.txt .

**Comment by ardywibowo** [comment]
Thanks!
I wasn't able to reproduce the ImageNet-100 results. For the first task, I'm getting only 92.4% accuracy vs. ~98% shown in Figure 6. I'm using the config `imagenet-100/b0_10s/configs/`. Am I missing something?

Edit: I just saw that the plot was for top-5 accuracy. In that case I'm getting the same accuracy. Checking for the other tasks now.

**Comment by ardywibowo** [comment]
Accuracy looks good. Thanks!
