### ISSUE TITLE
question

### ISSUE THREAD

**Issue by DRSAD** [Rhyssiyan/DER-ClassIL.pytorch#3]
After reading your paper, I have some questions
1.What is the accuracy of the model without the warm-up strategy? 
2.What is the data enhancement used by the model? 
3.What is the number of images stored?

**Comment by DRSAD** [comment]
4.In Figure 5, why is the initial accuracy of icarl and wa so different from other methods

**Comment by Rhyssiyan** [comment]
1. The accuracy is similar. About 0.2% accuracy gap. 
2. Data Augmentation:
* CIFAR-100 dataset：
     - RandomCrop
     - RandomHorizontalFlip
     - Normalize
* ImageNet100 and ImageNet1000 dataset
    - RandomResizedCrop
    - HorizontalFlip
    - Normalize
3. It depends on the protocol. For the B0 benchmark, we save 2000 images for CIFAR-100 and ImageNet-100 dataset and 20000 images for ImageNet-1000 dataset. For the B50 benchmark, we save 20 images for each class.
4. Thanks for your pointing out. We are not sure of the reason yet. We will reply to you after check in detail.
