### ISSUE TITLE
50 initial classes then 50 increments of 1 class

### ISSUE THREAD

**Issue by arthurdouillard** [Rhyssiyan/DER-ClassIL.pytorch#4]
Have you try (using your terminology) B50 50 steps?

It's quite challenging and models follow there a different regimes, I'd be interested to know your results.

**Comment by Rhyssiyan** [comment]
Hey, thanks for your attention.
For the DER(w/o pruning) based on modified resnet-32, the average accuracy is 64.31 and the final accuracy is 56.11.

**Comment by Rhyssiyan** [comment]
Hey, thanks for your attention.
We  tried our method on CIFAR100-B50 50 steps and the results are as follows
For the DER(w/o pruning) based on modified ResNet-32, the average accuracy is 64.31 and the final accuracy is 56.11.
For the DER(w/o pruning) based on ResNet-18, the average accuracy is 72.39 and the final accuracy is 64.84.

**Comment by arthurdouillard** [comment]
Thanks for the info, and with pruning?

**Comment by Rhyssiyan** [comment]
The sparsity loss coefficient needs to be tuned to make the average number of parameters comparable with other methods. If there is an update of the result, I will update it in time here.

**Comment by arthurdouillard** [comment]
So your sparsity loss is tuned for every setting?

**Comment by Rhyssiyan** [comment]
@arthurdouillard 
1. Thanks for your advice. The class ordering is stated in the ``dataset.py`` for each dataset. Specifically, we adopt the same 100 classes as PODNet for ImageNet100.

2. The results w/ pruning
resnet18 w/ pruning 
avg #paras:  5.0625M   avg acc:71.22
modified resnet32 w/pruning:
avg #paras: 0.856M      avg acc: 64.83

3. Sparsity loss coefficient:
Yes. We tune the sparsity loss coefficient for each dataset to make the number of parameters comparable. Concrete configurations can refer to our supplementary material.

**Comment by arthurdouillard** [comment]
Thanks for your answers!
