### ISSUE TITLE
Can you release some configuration files first?

### ISSUE THREAD

**Issue by BinahHu** [Rhyssiyan/DER-ClassIL.pytorch#8]
Thank you for this nice work!

I am trying to reproduce some comparison methods using the code and configurations from  [arthurdouillard/incremental_learning.pytorch](https://github.com/arthurdouillard/incremental_learning.pytorch). But the results in b0 setting are very different from what are reported in your paper. I guess the main reason is the configuration for some hyperparameters. I believe you have carefully tuned these parameters in b0 setting.

Since you said that your code is also based on [arthurdouillard/incremental_learning.pytorch](https://github.com/arthurdouillard/incremental_learning.pytorch), I am wondering if it is possible for you to release some configuration files first so that we reproduce some results using your setting and arthurdouillard's code?

Thank you so much!

**Comment by Rhyssiyan** [comment]
Hello, can you tell me that what your results are in b0 setting? (CIFAR b0-10steps?)  I remember that the experimental results using configurations in exps/der_wo_mask folders have been checked.

**Comment by BinahHu** [comment]
The results for der_wo_mask model are consistent with the results in your paper. What I want to say is that, could you please release some configurations for the comparison methods (for example UCIR, PODNet, BiC) so that we can reproduce these model in b0 setting.

**Comment by Rhyssiyan** [comment]
Hi, we have released the config of WA. We will release the configurations of other methods later.
