### ISSUE TITLE
Class ordering on CIFAR100

### ISSUE THREAD

**Issue by arthurdouillard** [Rhyssiyan/DER-ClassIL.pytorch#9]
Hey,

I see that your paper states that on CIFAR100-B0 you averaged three runs (cf caption of table 1). However in datasets.py, the dataset is defined with three runs (two news runs, and the three from PODNet).

Can I assume you only used the three from PODNet?

Thanks!

**Comment by Rhyssiyan** [comment]
Yes, that's right.
